### ISSUE TITLE
Set up initial admin user on remote server  (docker)

### ISSUE THREAD

**Issue by nn-afly** [chriseldredge/Klondike#201]
I must be missing something simple here, I'm using this docker image if it matters https://hub.docker.com/r/didstopia/nuget-klondike

Installs fine, but have added to remote server so no automatic admin ability. How can I create a admin user?

**Comment by chriseldredge** [comment]
This project is unrelated to the docker image you refer to. However, the page you link to has instructions for creating users, and you can also set a hard-coded API Key in Settings.config and use that from the command line (e.g. with `curl`) to execute administrative commands.
